addons/charting-tool/charting/src/main/java/org/openesb/tools/charting/persist/ChartBean.java
/*
 * BEGIN_HEADER - DO NOT EDIT
 *
 * The contents of this file are subject to the terms
 * of the Common Development and Distribution License
 * (the "License").  You may not use this file except
 * in compliance with the License.
 *
 * You can obtain a copy of the license at
 * https://open-esb.dev.java.net/public/CDDLv1.0.html.
 * See the License for the specific language governing
 * permissions and limitations under the License.
 *
 * When distributing Covered Code, include this CDDL
 * HEADER in each file and include the License file at
 * https://open-esb.dev.java.net/public/CDDLv1.0.html.
 * If applicable add the following below this CDDL HEADER,
 * with the fields enclosed by brackets "[]" replaced with
 * your own identifying information: Portions Copyright
 * [year] [name of copyright owner]
 */

/*
 * @(#)ChartBean.java
 * Copyright 2004-2007 Sun Microsystems, Inc. All Rights Reserved.
 *
 * END_HEADER - DO NOT EDIT
 */
package org.openesb.tools.charting.persist;

import org.openesb.tools.extchart.property.ChartPropertyGroupsBeanBasic;

/**
 *
 * @author rdwivedi
 */
public class ChartBean {
    
    private String mCID = null;
    private String mCName = null;
    private String mCParentName = null;
    private String mCType = null;
    private ChartPropertyGroupsBeanBasic mChartProps = null;
    private String mDBID = null;
    private String mCParentGrpID = "133";
    
    /** Creates a new instance of ChartBean */
    public ChartBean() {
    }
    
    public void setChartName(String cn) {
        mCName = cn;
    }
    public void setChartParentName(String pn) {
        mCParentName = pn;
    }
    public String getParentID() {
        return mCParentGrpID;
    }
    
    public void setParentID(String id){
        mCParentGrpID = id;
    }
    public void setChartID(String id) {
        mCID = id;
    }
    
    public void createNewChartID() {
        mCID = "_c" + System.currentTimeMillis();
    }
    public void setChartDataBeanID(String d) {
        mDBID = d;
    }
    
    public String getChartDataBeanID() {
        return mDBID;
    }
    public void setChartProperties(ChartPropertyGroupsBeanBasic d) {
        mChartProps = d;
    }
    public String getChartID() {
        return mCID;
    }
    public String getChartName() {
        return mCName;
    }
    public String getChartType() {
        return mCType;
    }
    public String getChartParentName() {
        return mCParentName;
    }
    
    public ChartPropertyGroupsBeanBasic getChartProperties() {
        if(mChartProps == null && mCType!=null ) {
            setChartPropertiesForDataset(null,mCType);
        }
        return mChartProps;
    }

    public void setChartPropertiesForDataset(String dsType, String cType) {
        mCType = cType;
        ChartPropertyGroupsBeanBasic g = new ChartPropertyGroupsBeanBasic();
        g.repopulate(cType);
        this.setChartProperties(g);
    }
    
    public void resetChartType(String cType) {
       mCType = cType;
       ChartPropertyGroupsBeanBasic g = this.getChartProperties();
       if(g==null){
           
          g = new ChartPropertyGroupsBeanBasic();
       }
       g.repopulate(cType); 
       this.setChartProperties(g);
    }
    //public void setChartType(String cType) {
    //     mCType = cType;
    //}
    
}

addons/charting-tool/charting/src/main/java/org/openesb/tools/charting/persist/DataBean.java
/*
 * BEGIN_HEADER - DO NOT EDIT
 *
 * The contents of this file are subject to the terms
 * of the Common Development and Distribution License
 * (the "License").  You may not use this file except
 * in compliance with the License.
 *
 * You can obtain a copy of the license at
 * https://open-esb.dev.java.net/public/CDDLv1.0.html.
 * See the License for the specific language governing
 * permissions and limitations under the License.
 *
 * When distributing Covered Code, include this CDDL
 * HEADER in each file and include the License file at
 * https://open-esb.dev.java.net/public/CDDLv1.0.html.
 * If applicable add the following below this CDDL HEADER,
 * with the fields enclosed by brackets "[]" replaced with
 * your own identifying information: Portions Copyright
 * [year] [name of copyright owner]
 */

/*
 * @(#)DataBean.java
 * Copyright 2004-2007 Sun Microsystems, Inc. All Rights Reserved.
 *
 * END_HEADER - DO NOT EDIT
 */
package org.openesb.tools.charting.persist;

import org.openesb.tools.extchart.exception.ChartException;
import org.openesb.tools.extchart.jfchart.data.DataAccess;
import org.openesb.tools.extchart.jfchart.data.SQLDataAccess;
import org.openesb.tools.extchart.jfchart.data.SampleDemoDataAccess;

/**
 *
 * @author rdwivedi
 */
public class DataBean {
    
    private String dbJndiName = null;
    private String displayName = null;
    private String mId = null;
    private String mQuery = null;
    private String mParentName = null;
    private String dataSetType = null;
    private String grpID = null;

    public DataBean(String dN, String pName) {
        displayName = dN;
        mParentName = pName;
        grpID = "12";
    }
    public String getDisplayName() {
        return displayName;
    }
    public String getJNDIName() {
        return dbJndiName;
    }
     public void setJNDIName(String jn) {
        dbJndiName = jn;
    }
    public void setID(String id) {
        mId = id;
    }
    public String getGroupID() {
     return grpID;   
    }
    public String getParentDisplayName() {
        return mParentName;
    }
    public void setQuery(String query) {
        mQuery = query;
    }
    public String getQuery() {
        return mQuery;
    }
     public void createNewID() {
        mId = "_d" + System.currentTimeMillis();
    }
     public String getID() {
         return mId;
     }
     public String getDataSetType() {
         return dataSetType;
     }
     public void setDataSetType(String ddsType) {
         dataSetType = ddsType;
     }
     public DataAccess getDataAccessObject() {
         if(dbJndiName == null || dbJndiName.length() < 1) {
             return new SampleDemoDataAccess(dataSetType);
         } else {
             return new SQLDataAccess(dbJndiName, dataSetType,getQuery());
         }
         
     }
     public boolean validate() throws ChartException {
         Object obj = getDataAccessObject().getDataSet();
         return obj!=null;
           
    }
}

addons/charting-tool/charting/src/main/webapp/chart/ChartPanel.jsp
<?xml version="1.0" encoding="UTF-8"?>
<jsp:root version="1.2" xmlns:extchart="http://open-esb.dev.java.net/extchart/extchart" 
    xmlns:f="http://java.sun.com/jsf/core" xmlns:h="http://java.sun.com/jsf/html"
    xmlns:jsp="http://java.sun.com/JSP/Page" xmlns:ui="http://www.sun.com/web/ui">
    <jsp:directive.page contentType="text/html;charset=UTF-8" pageEncoding="UTF-8"/>
    <f:view>
        <ui:page binding="#{chart$ChartPanel.page1}" id="page1">
            <ui:html binding="#{chart$ChartPanel.html1}" id="html1">
                <ui:head binding="#{chart$ChartPanel.head1}" id="head1">
                    <ui:link binding="#{chart$ChartPanel.link1}" id="link1" url="/resources/stylesheet.css"/>
                </ui:head>
                <ui:body binding="#{chart$ChartPanel.body1}" id="body1" style="-rave-layout: grid">
                    <ui:form binding="#{chart$ChartPanel.form1}" id="form1" target="workspaceFrame" >
                        <ui:label binding="#{chart$ChartPanel.label1}" id="label1" text="Chart Type"/>
                        <ui:dropDown action="#{chart$ChartPanel.submit_action}" binding="#{chart$ChartPanel.dropDown1}" id="dropDown1" items="#{chart$ChartPanel.options.options}"/>
                        <ui:button  action="#{chart$ChartPanel.button1_action}" binding="#{chart$ChartPanel.button1}" id="button1" text="Refresh"/>
                        <ui:button  action="#{chart$ChartPanel.button2_action}" binding="#{chart$ChartPanel.button2}" id="button2" text="Save"/>
                        </ui:form>
                        <extchart:extchart dataAccess="#{ChartApplicationBeansContainer.dataAccessBeanForCurrentChart.dataAccessObject}" id="id1" propertyGroups="#{ChartApplicationBeansContainer.currentChartBeanOnEditor.chartProperties}"/>
                </ui:body>
            </ui:html>
        </ui:page>
    </f:view>
</jsp:root>

addons/charting-tool/charting/src/main/webapp/chart/PropertyPane.jsp
<?xml version="1.0" encoding="UTF-8"?>
<jsp:root version="1.2" xmlns:f="http://java.sun.com/jsf/core" 
xmlns:h="http://java.sun.com/jsf/html" 
xmlns:jsp="http://java.sun.com/JSP/Page" 
xmlns:ui="http://www.sun.com/web/ui"
xmlns:extps="http://open-esb.dev.java.net/extps/extps">
    <jsp:directive.page contentType="text/html;charset=UTF-8" pageEncoding="UTF-8"/>
    <script><![CDATA[
        function retrieveChartPanel(url) {
	if (window.XMLHttpRequest) { // Non-IE browsers
	    req = new XMLHttpRequest();
	    req.onreadystatechange = chartPanelChanged;
		try {
			netscape.security.PrivilegeManager.enablePrivilege("UniversalBrowserRead");
		} catch (e) {
			//alert("Permission UniversalBrowserRead denied.");
		}
		try {
			req.open("GET", url, true);
		} catch (e) {
			alert(e);
		}
		req.send(null);
	} else if (window.ActiveXObject) { // IE
		req = new ActiveXObject("Microsoft.XMLHTTP");
		if (req) {
			req.onreadystatechange = chartPanelChanged;
			req.open("GET", url, true);
			req.send();
		}
	}
}

function chartPanelChanged() {
	//displayWait();
	if (req.readyState == 4) { // Complete
		if (req.status == 200) { // OK response
			//ajaxAction();
                        updateChartPanel()
		} else {
			alert("Problem: " + req.statusText);
		}
	}
}

function updateChartPanel() {
	var ajaxResponse = req.responseText;	//.split("\n");
        
	var chartBlockDiv = parent.frames['chartPreviewFrame'].document.getElementById("_imgProp");
        
        //alert("The block id is " + chartBlockDiv);
	chartBlockDiv.innerHTML = ajaxResponse;
	 
}

function updateChart() {
//alert("update chart is called");
//alert("AS" + parent.frames['chartPreviewFrame'].document.getElementById("_imgProp"));
var randomnumber=Math.random()*5;
        retrieveChartPanel("chartPanel.jsp?chartBeanIdentifier=ChartEditorBean&rnd=" +randomnumber);
}

function doNothing() {
}
                         ]]></script>
                 
    <f:view>
        <ui:page binding="#{chart$PropertyPane.page1}" id="page1">
            <ui:html binding="#{chart$PropertyPane.html1}" id="html1">
                <ui:head binding="#{chart$PropertyPane.head1}" id="head1">
                    <ui:link binding="#{chart$PropertyPane.link1}" id="link1" url="/resources/stylesheet.css"/>
                </ui:head>
                
                <ui:body binding="#{chart$PropertyPane.body1}" id="body1" style="-rave-layout: grid">
                    <ui:form binding="#{chart$PropertyPane.form1}" id="form1">
                        <extps:extps  id="id1"   propertyGroups="#{ChartApplicationBeansContainer.currentChartBeanOnEditor.chartProperties}" resourceBundle = "ChartProperties"/> 
                        <script><![CDATA[
                        parent.frames['chartPreviewFrame'].document.location='../chart/ChartPanel.jsp';
                           // parent.frames['chartPreviewFrame'].src="../layout/ChartConfigLayout.jsp";
                        ]]></script>
                    </ui:form>
                </ui:body>
            </ui:html>
        </ui:page>
    </f:view>
</jsp:root>